<a href="https://colab.research.google.com/github/Void-Brain70/Python/blob/master/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [5]:
# Dataset
D = array([[4,11],[8,4],[13,5],[7,14]])

In [6]:
print(D)

[[ 4 11]
 [ 8  4]
 [13  5]
 [ 7 14]]


In [7]:
# Transpose
print(D.T)

[[ 4  8 13  7]
 [11  4  5 14]]


In [8]:
# Mean calculation
M = mean(D.T,axis=1)
print(M)

[8.  8.5]


In [9]:
A = D - M
print(A)

[[-4.   2.5]
 [ 0.  -4.5]
 [ 5.  -3.5]
 [-1.   5.5]]


In [10]:
# Covariance Matrix
C = cov(A.T)
print(C)

[[ 14. -11.]
 [-11.  23.]]


In [12]:
# Calculating eigenvalues
values ,vectors = eig(C)

In [13]:
print(values)

[ 6.61513568 30.38486432]


In [14]:
print(vectors)

[[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]


In [15]:
# Calculating principle component
pca = vectors.T.dot(A.T)

print(pca)


[[ 1.92752836  2.50825486 -2.20038921 -2.23539401]
 [-4.30518692  3.73612869  5.69282771 -5.12376947]]
